version: "3.9"
services:
  app:
    build: .
    container_name: book-rec-app
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped

