name: Deploy to EC2

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '**/*.md'
      - 'deployment/docs/**'

env:
  PROJECT_DIR: /opt/app/repo

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /opt/app/repo
          git fetch --all
          git reset --hard origin/main
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d --build
          sudo docker system prune -f
